import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';
import {readFavorites,createAppearance,readAppearance,restoreFavorite,FAVORITES_START,PRESET_SIZE} from '../public/eversave/appearance.mjs';
import {ACCOUNT,ACCOUNT_DATA,PROFILE_FLAGS} from '../public/eversave/parser.mjs';import {md5} from '../public/eversave/md5.mjs';import {sliderGroups} from '../public/eversave/sliders.mjs';import {preset} from './helpers.mjs';
function synthetic(){const buffer=new ArrayBuffer(ACCOUNT_DATA+0x60000),b=new Uint8Array(buffer);b.set(new TextEncoder().encode('BND4'));new DataView(buffer).setUint32(ACCOUNT_DATA,1,true);b.set(md5(b.subarray(ACCOUNT_DATA)),ACCOUNT);return buffer;}
test('archive round trip preserves all 304 bytes including opaque data',async()=>{const raw=preset();raw[16]=201;raw[17]=77;const p=await createAppearance(raw,'Test');assert.deepEqual((await readAppearance(JSON.parse(JSON.stringify(p)))).raw,raw);const tampered={...p,preset:btoa(String.fromCharCode(...raw.map((v,i)=>i===80?12:v)))};await assert.rejects(()=>readAppearance(tampered),/checksum/);});
test('one favorite and account checksum are the only mutable ranges',()=>{const a=synthetic(),b=restoreFavorite(a,preset(),15),original=new Uint8Array(a),changed=new Uint8Array(b),start=FAVORITES_START+14*PRESET_SIZE;for(let i=0;i<changed.length;i++)if(original[i]!==changed[i])assert.ok((i>=start&&i<start+PRESET_SIZE)||(i>=ACCOUNT&&i<ACCOUNT_DATA));assert.equal(readFavorites(b).report.accountChecksum,'valid');assert.equal(readFavorites(b).favorites[14].empty,false);assert.equal(readFavorites(a).favorites[14].empty,true);});
test('invalid slots, damaged accounts, and unsupported structures are rejected',()=>{const a=synthetic();for(const slot of [0,16,1.5])assert.throws(()=>restoreFavorite(a,preset(),slot));new Uint8Array(a)[ACCOUNT_DATA+100]=33;assert.throws(()=>restoreFavorite(a,preset(),1),/warnings/);const p=preset();p[24]=0;assert.throws(()=>restoreFavorite(synthetic(),p,1),/structure/);});
test('model IDs are translated to menu numbers, unknown IDs stay unconfirmed',()=>{const p=preset();p[40]=106;p[36]=152;const g=sliderGroups(p);assert.equal(g.find(x=>x.category==='Hair').values[0].value,22);assert.equal(g.find(x=>x.category==='Adjust Face Template').values[0].unmapped,true);assert.equal(sliderGroups(p,{bone:6}).find(x=>x.category==='Adjust Face Template').values[0].value,6);});
test('manual selector metadata is validated',async()=>{const p=await createAppearance(preset());await assert.rejects(()=>readAppearance({...p,manualValues:{bone:152}}),/selector/);await assert.rejects(()=>readAppearance({...p,manualValues:{unknown:1}}),/selector/);});
for(const path of ['../ER0000.sl2','../ER0000(2).sl2'])test('real save byte preservation: '+path,{skip:!existsSync(path)},async()=>{const file=readFileSync(path),a=file.buffer.slice(file.byteOffset,file.byteOffset+file.byteLength),f=readFavorites(a);assert.equal(f.report.accountChecksum,'valid');assert.ok(f.favorites.every(x=>!x.issue));const active=f.favorites.find(x=>!x.empty);if(!active)return;const archive=await createAppearance(active.raw);assert.deepEqual((await readAppearance(archive)).raw,active.raw);const b=restoreFavorite(a,active.raw,15);assert.equal(readFavorites(b).report.accountChecksum,'valid');assert.deepEqual(new Uint8Array(a).subarray(0,ACCOUNT),new Uint8Array(b).subarray(0,ACCOUNT));assert.deepEqual(new Uint8Array(a).subarray(PROFILE_FLAGS),new Uint8Array(b).subarray(PROFILE_FLAGS));});
